### ISSUE TITLE
Error in cover with 0 hp creatures

### ISSUE THREAD

**Issue by Fridan99** [kandashi/dnd5e-helpers-cover-expansion#6]
It seems that there is some kind of error in the calculation of cover with creatures at 0 hp, when it is intended that they do NOT offer cover. 

![1](https://user-images.githubusercontent.com/86131373/138782292-32b2970c-8e47-4072-947b-f760c6fbf1e8.jpg)

![2](https://user-images.githubusercontent.com/86131373/138782315-1a7b610b-25b7-4399-ab3d-4dc592ecc934.jpg)

Then i remove the token concentrating in case it could cause some kind of error, but it remains the same.
![3](https://user-images.githubusercontent.com/86131373/138782409-6337906c-6bed-44d2-8eed-48ab4ce4a54e.jpg)

In the console there does not seem to be any error
![4](https://user-images.githubusercontent.com/86131373/138782461-1c0d6657-df37-4a29-acba-cd469dee4126.jpg)

The creature with 0 hp is a zombie, medium size.

**Comment by kandashi** [comment]
the issue you had was the spaces in the strings, this should be fixed in the latest version

**Comment by Fridan99** [comment]
I have recently upgraded to 0.1.05 and it seems that the error persists.....
![1](https://user-images.githubusercontent.com/86131373/139604232-02a4a776-0822-4a99-b55a-2677b970d742.jpg)

**Comment by Fridan99** [comment]
Any plans for this bug in the new Foundry V9? It only happens with linked actors as far as I know.
